### PR TITLE
Update usa-table to match SDS table appearance

### PR DESCRIPTION
**Pull request by cwolf10**

### CODE REVIEW

**Comment by Bibek-Regmi** [comment]
Build seems to have failed

**Comment by Bibek-Regmi** [comment]
@cwolf10 Would these changes be breaking if applied to master? I think ideally, we'd want these changes to go into master branch, so when teams update to latest sam styles version, they get these changes and are able to use with the table

**Comment by cwolf10** [comment]
@Bibek-Regmi ngx-uswds is still using sam-styles@0.0.120-beta.2. Isn't break-theming the branch we are creating the beta versions off of?

**Comment by cwolf10** [comment]
If we are switching ngx-uswds back to using normal versions of sam-styles, I don't believe this would be a breaking change, but can double check before merging.

**Comment by Bibek-Regmi** [comment]
@cwolf10 the main reason for master is that the teams have requested to be able to use ngx-uswds and want the needed CSS to make it match mockups for our sam-styles table. Break-theming isn't queued for release as of yet, so if we can throw this into master without breaking sds-tables, then it'd allow teams to use ngx-uswds table alongside official sam-styles release

**Comment by cwolf10** [comment]
I've got what you're saying.. Too many package.json's to keep track of. Yeah need to push to master because the styling will be coming from sam-styles through SDS rather than from ngx-uswds package. Let me set up my local and verify we can merge to master and then I'll re-aim the PR.

**Comment by cwolf10** [comment]
Swapping aim of PR, will push changes needed for master and open another PR later today.

**Pull request closed without merging**
